version: '3'

services:

  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - './data:/data'
    tty: true
    stdin_open: true
    environment:
      EULA: 'TRUE'
      INIT_MEMORY: '2G'
      MAX_MEMORY: '3G'

  backups:
    image: itzg/mc-backup
    container_name: minecraft-server-backups
    restart: unless-stopped
    volumes:
      - './data:/data:ro'
      - './backups:/backups'
    environment:
      BACKUP_INTERVAL: '12h'
      RCON_HOST: minecraft
      PRUNE_BACKUPS_DAYS: 30
