version: '3'

services:

  mongo:
    image: mongo:4.4.6
    container_name: mongo-database
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - './data-vol:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: server
      MONGO_INITDB_ROOT_PASSWORD: server
