version: '3'

services:

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    volumes:
      - './data:/data'
      - './letsencrypt:/etc/letsencrypt'
    ports:
      - 81:81
      - 80:80
      - 443:443
