version: '3'

services:

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-reverse-proxy
    ports:
      - 30081:81
      - 30080:80
      - 30443:443
    volumes:
      - './data:/data'
      - './letsencrypt:/etc/letsencrypt'
