version: '3'

services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole-ad-blocker
    restart: unless-stopped
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8080:80/tcp'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    environment:
      TZ: 'Europe/Rome'
