version: '3'

services:

  postgres:
    image: postgres
    container_name: postgresql-database
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: server
