version: '3'

services:

  postgres:
    image: postgres
    container_name: postgresql-database
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: server

  phppgadmin:
    image: dpage/pgadmin4
    container_name: postgresql-phppgadmin
    restart: unless-stopped
    ports:
      - 5050:5050
    volumes:
      - './pgadmin-data:/var/lib/pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: server@server.com
      PGADMIN_DEFAULT_PASSWORD: server
