version: '3'

services:

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-vpn-server
    restart: unless-stopped
    ports:
      - 51820:51820/udp
    volumes:
      - '/config:/config'
      - '/modules:/lib/modules'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SERVERURL=vpn.favo02.dev
      - PEERS=1
      - ALLOWEDIPS=0.0.0.0/0
