version: '3'

services:

  teamspeak:
    image: teamspeak:latest
    container_name: teamspeak-server
    restart: unless-stopped
    ports:
      - ${PORT_1}:9987/udp
      - ${PORT_2}:10011
      - ${PORT_3}:30033
    volumes:
      - './teamspeak:/var/ts3server/'
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: ${DB_USER}
      TS3SERVER_DB_PASSWORD: ${DB_PASSWORD}
      TS3SERVER_DB_NAME: ${DB_NAME}
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept

  db:
    image: mariadb:latest
    container_name: teamspeak-mariadb
    restart: unless-stopped
    volumes:
      - './maria_db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
