version: '3'

services:

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    ports:
      - ${PORT}:9091
    volumes:
      - './authelia-data/config:/config'
