version: '3'

services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole-ad-blocker
    restart: unless-stopped
    ports:
      - ${PORT_1}:53/tcp
      - ${PORT_1}:53/udp
      - ${PORT_2}:80/tcp
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    environment:
      TZ: ${TIMEZONE}
