# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark
jwt_secret: ${SECRET_1}

default_redirection_url: ${ROOT_DOMAIN}

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

totp:
  issuer: ${ROOT_DOMAIN}
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: true
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 2

access_control:
  default_policy: deny
  rules:
    - domain: "${AUTH_DOMAIN}"
      policy: bypass
    - domain: "${PROT_DOMAIN_1}"
      policy: two_factor

session:
  name: authelia_session
  secret: ${SECRET_2}
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: ${ROOT_DOMAIN}  # Should match whatever your root protected domain is

regulation:
  max_retries: 5
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: ${SECRET_3}

notifier:
  filesystem:
    filename: /config/notification.txt
