version: '3'

services:

  postgres:
    image: postgres:15 # cannot upgrade due to current data version
    container_name: postgresql-database
    restart: unless-stopped
    ports:
      - ${PORT}:5432
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${INIT_USERNAME}
      POSTGRES_PASSWORD: ${INIT_PASSWORD}
