version: '3'

services:

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    volumes:
      - './data:/data'
      - './letsencrypt:/etc/letsencrypt'
    ports:
      - ${PORT_1}:81
      - ${PORT_2}:80
      - ${PORT_3}:443
