version: '3'

services:

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-vpn
    restart: unless-stopped
    ports:
      - ${PORT}:51820/udp
    volumes:
      - '/opt/wireguard-server/config:/config'
      - '/lib/modules:/lib/modules'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - SERVERURL=${DOMAIN}
      - PEERS=${PEERS_NUMBER}
      - ALLOWEDIPS=${ALLOWED_IPS}
