version: '3'

services:

  web:
    image: nginx:latest
    container_name: nginx-webserver
    ports:
      - 8080:80
    volumes:
      - './src:/var/www/html'
      - './default.conf:/etc/nginx/conf.d/default.conf'
    links:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    container_name: nginx-webserver-php
    volumes:
      - './src:/var/www/html'
